move:
  action_name: /admittance_controller/admittance
ft_reset_services: [/right_arm_gravity_compensation/calibrate_bias, /left_arm_gravity_compensation/calibrate_bias]
right_arm:
  pose: [0.424, -0.132, 0.151, 0.214, 0.682, 0.683, 0.154] # when case arm
  # pose: [0.473, -0.125, 0.148, 0.246, 0.663, 0.684, 0.181] # when probe arm
